#!/bin/bash

echo "run pre commit hook"

set -e

while read oldrev newrev refname; do
  branch=$(git rev-parse --symbolic --abbrev-ref $refname)
  echo "branch is $branch"
done

echo "check tests"
./gradlew test
